"""Add profile_pic_filename to usuarios table

Revision ID: 7e1e5efd1700
Revises: 
Create Date: 2025-10-21 00:51:28.630161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e1e5efd1700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteiras', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('criado_em',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_usuario'))

    with op.batch_alter_table('categorias_transacoes', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('criado_em',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('nome'))

    with op.batch_alter_table('saldos', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('criado_em',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('ult_atualizacao',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_carteira'))

    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('criado_em',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_carteira'))
        batch_op.drop_index(batch_op.f('idx_categoria'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.alter_column('criado_em',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('image')

    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_categoria'), ['id_categoria'], unique=False)
        batch_op.create_index(batch_op.f('idx_carteira'), ['id_carteira'], unique=False)
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))

    with op.batch_alter_table('saldos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_carteira'), ['id_carteira'], unique=False)
        batch_op.alter_column('ult_atualizacao',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))

    with op.batch_alter_table('categorias_transacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nome'), ['nome'], unique=True)
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('carteiras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usuario'), ['id_usuario'], unique=False)
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
